# --- 1. Redis 部署 (缓存层) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        # 【重要】换成你刚构建成功的 Redis ACR 地址
        image: crpi-isruoknymwjt6jux.cn-hangzhou.personal.cr.aliyuncs.com/dja-repo/redis:latest
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379

---
# --- 2. 后端部署 (Java 17 + MyBatis) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-backend
  template:
    metadata:
      labels:
        app: java-backend
    spec:
      imagePullSecrets:
      - name: aliyun-acr-secret
      containers:
      - name: java-backend
        image: crpi-isruoknymwjt6jux.cn-hangzhou.personal.cr.aliyuncs.com/dja-repo/java-app-auto:backend-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/k8s_monitor_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        # 重点：这里的 Host 必须对应上面的 Service Name
        - name: SPRING_REDIS_HOST
          value: "redis-service"
        - name: SPRING_REDIS_PORT
          value: "6379"

---
apiVersion: v1
kind: Service
metadata:
  name: java-backend-service
spec:
  type: NodePort
  selector:
    app: java-backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080

---
# --- 3. 前端部署 (Vue 3 + Nginx) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vue-frontend
  template:
    metadata:
      labels:
        app: vue-frontend
    spec:
      imagePullSecrets:
      - name: aliyun-acr-secret
      containers:
      - name: vue-frontend
        image: crpi-isruoknymwjt6jux.cn-hangzhou.personal.cr.aliyuncs.com/dja-repo/java-app-auto:frontend-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: vue-frontend-service
spec:
  type: NodePort
  selector:
    app: vue-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001