# 数据库连接：重点！mysql-service 是你 K8s Service 的名字
spring.datasource.url=jdbc:mysql://mysql-service:3306/k8s_monitor_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=123456

# MyBatis 配置
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.demo.entity

# 显示 SQL 日志（方便调试）
logging.level.com.example.demo.mapper=debug